### ISSUE TITLE
fix osm login

### ISSUE THREAD

**Issue by timwaters** [timwaters/mapwarper#155]
I imagine that http is now https permanently 

our logs show

Net::HTTPRetriableError (301 "Moved Permanently"):
  /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http/response.rb:122:in `error!'
  oauth (0.5.3) lib/oauth/consumer.rb:233:in `token_request'

https://github.com/sozialhelden/omniauth-osm

**Comment by timwaters** [comment]
onfig.omniauth :osm, APP_CONFIG["omniauth_osm_key"], APP_CONFIG["omniauth_osm_secret"], {:client_options => {:site => "https://www.openstreetmap.org"}}
