### ISSUE TITLE
NoMethodError for geosearch

### ISSUE THREAD

**Issue by junranlei** [timwaters/mapwarper#191]
received following error when accessing /layers/geosearch
Called from /var/lib/gems/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
  ActiveRecord::SchemaMigration Load (0.5ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by LayersController#geosearch as HTML
   (0.7ms)  SELECT MIN("maps"."issue_year") FROM "maps"
Completed 500 Internal Server Error in 63ms (ActiveRecord: 9.9ms)

NoMethodError (undefined method `-' for nil:NilClass):
  app/controllers/layers_controller.rb:135:in `geosearch'

**Comment by junranlei** [comment]
This problem disappeared after uploading first map.
