### ISSUE TITLE
RMS Error if more than 3 gcps each with lat and lon and 0,0 and when rectified locking rectify tab

### ISSUE THREAD

**Issue by timwaters** [timwaters/mapwarper#97]
If a user just adds points to the source map and leaves the base map with 0,0 and hits rectify, there is an error when showing the rectify tab. Due to unable to calculate the RMS errror.

TypeError (can't convert ExceptionForMatrix::ErrNotRegular into String):
  lib/error_calculator.rb:95:in `rescue in calc_error'
  lib/error_calculator.rb:13:in`calc_error'
  app/models/map.rb:523:in `gcps_with_error'
  app/controllers/maps_controller.rb:633:in`warp'

**Comment by timwaters** [comment]
should be fixed now
